# Generated by Django 5.0.3 on 2024-04-17 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SighUp',
            new_name='SignUp',
        ),
        migrations.AlterModelOptions(
            name='signup',
            options={'verbose_name': 'SignUp', 'verbose_name_plural': 'SignUp'},
        ),
    ]
